#!/bin/sh

# Check coverage.  If configured without --coverage in CFLAGS,
# this will likely just get skipped.  (eg, configure with
# CFLAGS='--coverage -g -O0' to enable this test)

if ! test -f find-canvas-test.gcda; then
	exit 77
fi
RV=0

for name in \
	cset \
	find-canvas-test \
	handler \
	main \
	sttm-test \
	sttm \
	vtparser \
	;
do
	if test -f .libs/$name.gcno; then
		arg='-o .libs'
	else
		unset arg
	fi
	gcov $name $arg
	if < "$name".c.gcov sed \
			-e '\@{ /\* uncovered block \*/@,'"$( :
				)"'\@} /\* end uncovered \*/@d' \
			-e '/#####/!d' \
			-e '\@/\* uncovered \*/@d' | grep .; then
		echo The above lines were not executed during testing
		RV=77  # Skip this until such time as we actually have coverage
	fi >&2
done
	exit $RV
