name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: autoreconf -ivf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make dist
      run: make dist
